/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        StandardCalculator calc = new StandardCalculator();
        calc.add(1, 2);
        //calc.result = -1;
        System.out.println(calc.getResult());
        calc.clearResult();
        
        calc.add(Double.MAX_VALUE, Double.MAX_VALUE);

        calc.printResult();

        
        LogicCalculator calc1 = new LogicCalculator();

        calc1.OR(8, 6);

        calc1.printResult();

    }
}